# Generated by Django 5.2.8 on 2025-11-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown Event type"),
                    ("created", "Create Event"),
                    ("viewed", "Viewed Event"),
                    ("saved", "Save or update Event"),
                ],
                default="viewed",
                max_length=40,
            ),
        ),
    ]
