# Generated by Django 5.2.8 on 2025-11-25 08:42

import django.utils.timezone
import timescale.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_event_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="event",
            name="time",
            field=timescale.db.models.fields.TimescaleDateTimeField(
                default=django.utils.timezone.now, interval="1 day"
            ),
            preserve_default=False,
        ),
    ]
